# R4 Mark A

In [164]:
import pandas as pd
import tensorflow as tf

In [165]:
df = pd.read_csv('../exportedDataframe/features.csv')

In [166]:
df.head(5)

   ImagesName       CDR      VCDR       RDR    I    S    N    T  Labels
0   Negative1  0.543767  0.442765  0.116711  220  205  131  140       0
1  Negative10  0.410188  0.344595  0.088472  193  226  112  188       0
2  Negative11  0.431755  0.389447  0.231198  169  151  130  128       0
3  Negative12  0.388740  0.375648  0.131367  171  173  109  180       0
4  Negative13  0.408971  0.388471  0.147757  169  188  123  173       0

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ImagesName  168 non-null    object
 1   CDR         168 non-null    float64
 2   VCDR        168 non-null    float64
 3   RDR         168 non-null    float64
 4   I           168 non-null    int64
 5   S           168 non-null    int64
 6   N           168 non-null    int64
 7   T           168 non-null    int64
 8   Labels      168 non-null    int64
dtypes: float64(3), int64(5), object(1)
memory usage: 11.9+ KB

## Trial 1

In [168]:
df2 = df.copy(deep=True)

In [169]:
df2

     ImagesName       CDR      VCDR       RDR    I    S    N    T  Labels
0     Negative1  0.543767  0.442765  0.116711  220  205  131  140       0
1    Negative10  0.410188  0.344595  0.088472  193  226  112  188       0
2    Negative11  0.431755  0.389447  0.231198  169  151  130  128       0
3    Negative12  0.388740  0.375648  0.131367  171  173  109  180       0
4    Negative13  0.408971  0.388471  0.147757  169  188  123  173       0
..          ...       ...       ...       ...  ...  ...  ...  ...     ...
163  Positive81  0.424157  0.399471  0.235955  149  144  133  122       1
164  Positive82  0.447977  0.487421  0.167630  125  121  126  141       1
165  Positive83  0.426710  0.454861  0.166124  120  101  110  122       1
166  Positive84  0.345794  0.385417  0.233645  110  114  140  108       1
167   Positive9  0.337176  0.362229  0.175793  167  157    3  166       1

[168 rows x 9 columns]

In [170]:
df2.drop('ImagesName', inplace=True, axis=1)

In [171]:
df2

          CDR      VCDR       RDR    I    S    N    T  Labels
0    0.543767  0.442765  0.116711  220  205  131  140       0
1    0.410188  0.344595  0.088472  193  226  112  188       0
2    0.431755  0.389447  0.231198  169  151  130  128       0
3    0.388740  0.375648  0.131367  171  173  109  180       0
4    0.408971  0.388471  0.147757  169  188  123  173       0
..        ...       ...       ...  ...  ...  ...  ...     ...
163  0.424157  0.399471  0.235955  149  144  133  122       1
164  0.447977  0.487421  0.167630  125  121  126  141       1
165  0.426710  0.454861  0.166124  120  101  110  122       1
166  0.345794  0.385417  0.233645  110  114  140  108       1
167  0.337176  0.362229  0.175793  167  157    3  166       1

[168 rows x 8 columns]

In [172]:
from sklearn.model_selection import train_test_split

In [173]:
X = df2.drop('Labels', axis=1)
y = df2['Labels']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, random_state=42
)

In [174]:
from sklearn.preprocessing import StandardScaler

In [175]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [176]:
tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(7, activation='relu'), # 4,5,7,1
    tf.keras.layers.Dense(2, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss=tf.keras.losses.binary_crossentropy,
    optimizer=tf.keras.optimizers.Adam(lr=0.05),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name='accuracy'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

history = model.fit(X_train_scaled, y_train, epochs=30)

Epoch 1/30

/home/tsdhrm/.local/share/virtualenvs/ayoluluss2-CxxF7UsW/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)

5/5 [==============================] - 1s 2ms/step - loss: 0.7019 - accuracy: 0.5000 - precision: 0.5181 - recall: 0.6143
Epoch 2/30
5/5 [==============================] - 0s 4ms/step - loss: 0.6870 - accuracy: 0.5299 - precision: 0.5263 - recall: 1.0000
Epoch 3/30
5/5 [==============================] - 0s 3ms/step - loss: 0.6592 - accuracy: 0.5224 - precision: 0.5224 - recall: 1.0000
Epoch 4/30
5/5 [==============================] - 0s 4ms/step - loss: 0.6074 - accuracy: 0.5299 - precision: 0.5263 - recall: 1.0000
Epoch 5/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5957 - accuracy: 0.6716 - precision: 0.7241 - recall: 0.6000
Epoch 6/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5670 - accuracy: 0.7388 - precision: 0.8571 - recall: 0.6000
Epoch 7/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5656 - accuracy: 0.7239 - precision: 0.8667 - recall: 0.5571
Epoch 8/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5505 - accuracy: 0.7388 - precision: 0.8723 - recall: 0.5857
Epoch 9/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5495 - accuracy: 0.7090 - precision: 0.8605 - recall: 0.5286
Epoch 10/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5422 - accuracy: 0.7090 - precision: 0.8039 - recall: 0.5857
Epoch 11/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5469 - accuracy: 0.7090 - precision: 0.8163 - recall: 0.5714
Epoch 12/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5335 - accuracy: 0.7388 - precision: 0.8889 - recall: 0.5714
Epoch 13/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5238 - accuracy: 0.7388 - precision: 0.8723 - recall: 0.5857
Epoch 14/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5404 - accuracy: 0.7313 - precision: 0.8400 - recall: 0.6000
Epoch 15/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5265 - accuracy: 0.7313 - precision: 0.8696 - recall: 0.5714
Epoch 16/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5213 - accuracy: 0.7313 - precision: 0.9250 - recall: 0.5286
Epoch 17/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5319 - accuracy: 0.7239 - precision: 0.8235 - recall: 0.6000
Epoch 18/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5246 - accuracy: 0.7164 - precision: 0.8333 - recall: 0.5714
Epoch 19/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5192 - accuracy: 0.7537 - precision: 0.9744 - recall: 0.5429
Epoch 20/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5262 - accuracy: 0.7239 - precision: 0.8837 - recall: 0.5429
Epoch 21/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5136 - accuracy: 0.7388 - precision: 0.9070 - recall: 0.5571
Epoch 22/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5024 - accuracy: 0.7463 - precision: 0.9091 - recall: 0.5714
Epoch 23/30
5/5 [==============================] - 0s 4ms/step - loss: 0.4939 - accuracy: 0.7537 - precision: 0.9302 - recall: 0.5714
Epoch 24/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5079 - accuracy: 0.7164 - precision: 0.8333 - recall: 0.5714
Epoch 25/30
5/5 [==============================] - 0s 3ms/step - loss: 0.4982 - accuracy: 0.7239 - precision: 0.8511 - recall: 0.5714
Epoch 26/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5197 - accuracy: 0.7463 - precision: 0.9737 - recall: 0.5286
Epoch 27/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5106 - accuracy: 0.7164 - precision: 0.9211 - recall: 0.5000
Epoch 28/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5227 - accuracy: 0.7164 - precision: 0.8636 - recall: 0.5429
Epoch 29/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5001 - accuracy: 0.7388 - precision: 0.9070 - recall: 0.5571
Epoch 30/30
5/5 [==============================] - 0s 4ms/step - loss: 0.4788 - accuracy: 0.7463 - precision: 0.9500 - recall: 0.5429

In [177]:
predictions = model.predict(X_test_scaled)

2/2 [==============================] - 0s 2ms/step

In [178]:
import numpy as np

In [179]:
prediction_classes = [
    1 if prob > 0.5 else 0 for prob in np.ravel(predictions)
]

In [180]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

print(f'Accuracy: {accuracy_score(y_test, prediction_classes):.2f}')
print(f'Precision: {precision_score(y_test, prediction_classes):.2f}')
print(f'Recall: {recall_score(y_test, prediction_classes):.2f}')

Accuracy: 0.82
Precision: 0.90
Recall: 0.64